package src;
public enum AddableThingEnum{
	//Terrain types
	MOUNTAIN_TERRAIN, GRASS_TERRAIN,WATER_TERRAIN,WATER_MOUNTAIN_TERRAIN, OBSTACLE,
	//Entities
	VILLAGER_ENTITY,TRADER_ENTITY,MONSTER_ENTITY,AVATAR_ENTITY, KNIGHT_ENTITY,
	//Effect ITEMS
	HURT_EFFECT_ITEM, HEAL_EFFECT_ITEM,LEVEL_UP_EFFECT_ITEM,KILL_EFFECT_ENUM,
	//KEY/DOOR
	DOOR_KEY_ITEM,
	//Weapons
	SHIELD_ITEM,SWORD_ITEM,TWO_HAND_SWORD_ITEM,BOW_ITEM,STAFF_ITEM,
	//Other
	TELEPORT_ITEM,
	//Decals
	RED_CROSS_DECAL, GOLD_STAR_DECAL, SKULL_DECAL,
	//Traps
	HURT_TRAP,HEAL_TRAP,LEVELUP_TRAP,KILL_TRAP,
	//Potions
	KNIGHT_POTION, INVISIBILITY_SERUM
}
